Npc
Danila01010101/OneButtonDefence pull request #1
Opened 2024-10-21 12:40 UTC by SposobWQ

2024-10-21 13:27 UTC, Danila01010101 requested changes

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationMillitary.cs
> +    private IEnumerator SpawnGnomes()
Отсутствует пустая строка перед новым методом.

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationMillitary.cs
> +    private IEnumerator AnimationWarriors(GameObject gnome)
Здесь то же самое.

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationMillitary.cs
> +            for (int i = 0; i < Path[index].Path.Count; i++)
Так же пишу на счет форматирования, перед и после цикла или блока if для его логического отделения от остального кода нужна пустая строка.

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationCitadel.cs
> +    public Color startvalue;
Не очень понятно для чего эти переменные публичны, стоит заменить модификатор доступа на private и добавить атрибут SerializeField

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationFabric.cs
> +    public int ShakeVibrato = 10;
Здесь те же замечания на счет модификатора доступа как и в классе DOTweenAnimationCitadel.cs

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationMillitary.cs
> +    }
Оставлен пустой метод Start, стоит его убрать.
Так же исправить модификатор досутпа.

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/TestScriptForMAterial.cs
> +    private void Start()
Нет пустой строчки после переменных

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/TestScriptForMAterial.cs
> +    public void SetOpaque(Material material)
Нет пустой строчки перед методом

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/TestScriptForMAterial.cs
> +    public void SetTransparent(Material material)
Нет пустой строчки перед методом

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationFabric.cs
> +    void Start()
Оставлен не нужный комментарий к методу Start, все переменные публичные без причины.

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimationFabric.cs
> +    IEnumerator WorkersAnimation()
Нет пустой строчки перед методом

2024-10-21 13:27 UTC, Danila01010101 commented on Assets/Scripts/DOTweenAnimation.cs
> +    IEnumerator Growing()
Отсутствует модификатор доступа private, его стоит прописывать явно.

2024-10-22 11:10 UTC, SposobWQ commented on Assets/Scripts/TestScriptForMAterial.cs
> +    public void SetTransparent(Material material)
Это вообще вроде не нужный скрипт

2024-10-22 11:30 UTC, SposobWQ commented on Assets/Scripts/DOTweenAnimationMillitary.cs
> +    }
Он корутину запускает при этом у меня эта строчка есть

2024-10-22 11:31 UTC, SposobWQ commented on Assets/Scripts/DOTweenAnimationFabric.cs
> +    void Start()
Нету этого комментария у меня

2024-10-23 09:27 UTC, merged